# Generated by Django 6.0.5 on 2026-06-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='is_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='shop_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
