

@baseUrl = http://127.0.0.1:8080/api/
@access=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwNTc2MTIyLCJpYXQiOjE3ODA1NzU4MjIsImp0aSI6IjAyMTAyZGM1Y2UyNDQwYmZhYjcwNGZhOTVhNDFmNTI5IiwidXNlcl9pZCI6IjE1In0.21kvjyY96v5pIPj9sQthMI0WrSSdEX0S-qN8FVa7_HE
POST {{baseUrl}}accounts/register/
Content-Type: application/json

{
    "full_name" : "Amir Reza",
    "phone_number" : "0922562127",
    "password" : "amiroonreza1",
    "is_shop" : true,
    "shop_name" : "Amir Reza Shop",
    "shop_address" : "Tehran, Iran"
}


###
POST {{baseUrl}}accounts/login/
Content-Type: application/json

{
    "phone_number" : "09225621257",
    "password" : "amiroonreza1"
}


###

POST {{baseUrl}}accounts/send_otp/
Content-Type: application/json

{
    "phone_number" : "09225621257"
}


###


POST {{baseUrl}}accounts/login_otp/
Content-Type: application/json

{
    "phone_number" : "09225621257",
    "code" : "395491"
}

###

POST {{baseUrl}}accounts/verify_register/
Content-Type: application/json

{
    "phone_number" : "09123456781",
    "code" : "884731"
}

###

GET {{baseUrl}}accounts/profile/
Content-Type: application/json
Authorization: Bearer {{access}}

###

GET {{baseUrl}}products/
Content-Type: application/json
Authorization: Bearer {{access}}
###

POST {{baseUrl}}products/
Content-Type: application/json
Authorization: Bearer {{access}}

{


}


