# Generated by Django 6.0.5 on 2026-06-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
        ('sales', '0002_sale_is_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='debts', to='sales.saleitem'),
        ),
    ]
