# Generated by Django 6.0.5 on 2026-06-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_debt_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='items',
        ),
    ]
